name: Java CI

on:
  push:
  pull_request:
  schedule: [ cron: '52 3 * * 5' ] # weekly: At 03:52 on Friday

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build
        run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub verify
